[2025-02-08T12:41:13.591+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.post_to_elasticsearch manual__2025-02-08T12:40:57.038037+00:00 [queued]>
[2025-02-08T12:41:13.600+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.post_to_elasticsearch manual__2025-02-08T12:40:57.038037+00:00 [queued]>
[2025-02-08T12:41:13.600+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T12:41:13.600+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-08T12:41:13.600+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T12:41:13.614+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): post_to_elasticsearch> on 2025-02-08 12:40:57.038037+00:00
[2025-02-08T12:41:13.626+0000] {standard_task_runner.py:52} INFO - Started process 460 to run task
[2025-02-08T12:41:13.632+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_milestone_3', 'post_to_elasticsearch', 'manual__2025-02-08T12:40:57.038037+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_RizkySP_DAG.py', '--cfg-path', '/tmp/tmpf5uf_7bq', '--error-file', '/tmp/tmpgw0cv6js']
[2025-02-08T12:41:13.634+0000] {standard_task_runner.py:80} INFO - Job 108: Subtask post_to_elasticsearch
[2025-02-08T12:41:13.694+0000] {task_command.py:371} INFO - Running <TaskInstance: pipeline_milestone_3.post_to_elasticsearch manual__2025-02-08T12:40:57.038037+00:00 [running]> on host b33620135048
[2025-02-08T12:41:13.749+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=RizkySP
AIRFLOW_CTX_DAG_ID=pipeline_milestone_3
AIRFLOW_CTX_TASK_ID=post_to_elasticsearch
AIRFLOW_CTX_EXECUTION_DATE=2025-02-08T12:40:57.038037+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-08T12:40:57.038037+00:00
[2025-02-08T12:41:13.751+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_RizkySP_DAG.py", line 44, in post_to_elasticsearch
    "http:Elasticsearch:9200",
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 207, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 54, in _normalize_hosts
    if parsed_url.port:
  File "/usr/local/lib/python3.7/urllib/parse.py", line 172, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'Elasticsearch:9200'
[2025-02-08T12:41:13.762+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pipeline_milestone_3, task_id=post_to_elasticsearch, execution_date=20250208T124057, start_date=20250208T124113, end_date=20250208T124113
[2025-02-08T12:41:13.768+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 108 for task post_to_elasticsearch (invalid literal for int() with base 10: 'Elasticsearch:9200'; 460)
[2025-02-08T12:41:13.811+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-02-08T12:41:13.833+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
