[2025-02-08T10:49:03.849+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.fetch_from_postgres manual__2025-02-08T10:48:57.634291+00:00 [queued]>
[2025-02-08T10:49:04.829+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.fetch_from_postgres manual__2025-02-08T10:48:57.634291+00:00 [queued]>
[2025-02-08T10:49:04.840+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T10:49:04.848+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-08T10:49:04.861+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T10:49:08.451+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): fetch_from_postgres> on 2025-02-08 10:48:57.634291+00:00
[2025-02-08T10:49:09.055+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_milestone_3', 'fetch_from_postgres', 'manual__2025-02-08T10:48:57.634291+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_RizkySP_DAG.py', '--cfg-path', '/tmp/tmpd3314ugf', '--error-file', '/tmp/tmpwdo9kl07']
[2025-02-08T10:49:08.667+0000] {standard_task_runner.py:52} INFO - Started process 2101 to run task
[2025-02-08T10:49:09.115+0000] {standard_task_runner.py:80} INFO - Job 53: Subtask fetch_from_postgres
[2025-02-08T10:49:11.110+0000] {task_command.py:371} INFO - Running <TaskInstance: pipeline_milestone_3.fetch_from_postgres manual__2025-02-08T10:48:57.634291+00:00 [running]> on host b33620135048
[2025-02-08T10:49:11.564+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=RizkySP
AIRFLOW_CTX_DAG_ID=pipeline_milestone_3
AIRFLOW_CTX_TASK_ID=fetch_from_postgres
AIRFLOW_CTX_EXECUTION_DATE=2025-02-08T10:48:57.634291+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-08T10:48:57.634291+00:00
[2025-02-08T10:49:11.671+0000] {base.py:68} INFO - Using connection ID '***_postgres' for task execution.
[2025-02-08T10:49:13.154+0000] {python.py:173} INFO - Done. Returned value was: None
[2025-02-08T10:49:13.174+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=pipeline_milestone_3, task_id=fetch_from_postgres, execution_date=20250208T104857, start_date=20250208T104903, end_date=20250208T104913
[2025-02-08T10:49:13.235+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-08T10:49:13.290+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
