[2025-02-08T13:01:31.267+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.fetch_from_postgres manual__2025-02-08T13:01:29.655265+00:00 [queued]>
[2025-02-08T13:01:31.276+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.fetch_from_postgres manual__2025-02-08T13:01:29.655265+00:00 [queued]>
[2025-02-08T13:01:31.276+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T13:01:31.276+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-08T13:01:31.276+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T13:01:31.282+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): fetch_from_postgres> on 2025-02-08 13:01:29.655265+00:00
[2025-02-08T13:01:31.291+0000] {standard_task_runner.py:52} INFO - Started process 348 to run task
[2025-02-08T13:01:31.296+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_milestone_3', 'fetch_from_postgres', 'manual__2025-02-08T13:01:29.655265+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_RizkySP_DAG.py', '--cfg-path', '/tmp/tmpx48ph16k', '--error-file', '/tmp/tmpr06s1_y4']
[2025-02-08T13:01:31.297+0000] {standard_task_runner.py:80} INFO - Job 128: Subtask fetch_from_postgres
[2025-02-08T13:01:31.355+0000] {task_command.py:371} INFO - Running <TaskInstance: pipeline_milestone_3.fetch_from_postgres manual__2025-02-08T13:01:29.655265+00:00 [running]> on host b33620135048
[2025-02-08T13:01:31.398+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=RizkySP
AIRFLOW_CTX_DAG_ID=pipeline_milestone_3
AIRFLOW_CTX_TASK_ID=fetch_from_postgres
AIRFLOW_CTX_EXECUTION_DATE=2025-02-08T13:01:29.655265+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-08T13:01:29.655265+00:00
[2025-02-08T13:01:31.416+0000] {base.py:68} INFO - Using connection ID '***_postgres' for task execution.
[2025-02-08T13:01:34.315+0000] {python.py:173} INFO - Done. Returned value was: None
[2025-02-08T13:01:34.339+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=pipeline_milestone_3, task_id=fetch_from_postgres, execution_date=20250208T130129, start_date=20250208T130131, end_date=20250208T130134
[2025-02-08T13:01:34.369+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-08T13:01:34.407+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
